-- lua/plugins/formatters.lua
return {
    -- "stevearc/conform.nvim",
    -- event = { "BufReadPre", "BufNewFile" },
    -- config = function()
    --     local conform = require("conform")
    --
    --     conform.setup({
    --         notify_on_error = false,
    --         formatters_by_ft = {
    --             python = { "isort", "black" }, -- first isort, then black
    --         },
    --     })
    --
    --     local grp = vim.api.nvim_create_augroup("ConformFormatPython", { clear = true })
    --     vim.api.nvim_create_autocmd("BufWritePre", {
    --         group = grp,
    --         pattern = "*.py",
    --         callback = function(args)
    --             conform.format({
    --                 bufnr = args.buf,
    --                 async = false,
    --                 timeout_ms = 5000,
    --                 lsp_fallback = false,
    --             })
    --         end,
    --     })
    -- end,
}
